# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTss < Formula
  desc "Ba dum, tss!"
  homepage "https://github.com/maleynikov/homebrew-tap"
  version "0.1.9"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://gitlab.maleynikov.tech/api/v4/projects/23/packages/generic/tss/v0.1.9/tss_Darwin_arm64.tar.gz?private_token=7W6yQkYCDW1pbaPmazVQ"
      sha256 "810bfba935daa2442c1a3f905c23a5727e5eaf427c45919f37a7113bf6220e94"

      def install
        bin.install "tss"
      end
    end
    if Hardware::CPU.intel?
      url "https://gitlab.maleynikov.tech/api/v4/projects/23/packages/generic/tss/v0.1.9/tss_Darwin_x86_64.tar.gz?private_token=7W6yQkYCDW1pbaPmazVQ"
      sha256 "0ab47eb73ea8212431c11c642c44e91609568b1a4b76180c29112c2cddcc7a9b"

      def install
        bin.install "tss"
      end
    end
  end
end
