# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTss < Formula
  desc "Ba dum, tss!"
  homepage "https://github.com/maleynikov/homebrew-tap"
  version "0.1.7"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://gitlab.maleynikov.tech/maleynikov/tss/-/releases/v0.1.7/downloads/tss_Darwin_arm64.tar.gz"
      sha256 "4bc3686eb861346693ea2c831d6b21e4cc96e1acfc49d1d69d23bdb51772c19a"

      def install
        bin.install "tss"
      end
    end
    if Hardware::CPU.intel?
      url "https://gitlab.maleynikov.tech/maleynikov/tss/-/releases/v0.1.7/downloads/tss_Darwin_x86_64.tar.gz"
      sha256 "b6a93d525a595d6b07d9cc65484005244cd02474dd62e6b70af297cf681981ac"

      def install
        bin.install "tss"
      end
    end
  end
end
