# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTss < Formula
  desc "Ba dum, tss!"
  homepage "https://github.com/maleynikov/homebrew-tap"
  version "0.1.6"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://gitlab.maleynikov.tech/maleynikov/tss/-/releases/v0.1.1/downloads/v0.1.6/tss_Darwin_arm64.tar.gz"
      sha256 "c24621bb2279bf404e453da278cf3ea9e5b3cfdc40a5280011229c656a92fcb4"

      def install
        bin.install "tss"
      end
    end
    if Hardware::CPU.intel?
      url "https://gitlab.maleynikov.tech/maleynikov/tss/-/releases/v0.1.1/downloads/v0.1.6/tss_Darwin_x86_64.tar.gz"
      sha256 "4fe766fc7d0a6d65df9eb7e358760686242885a5543c71fedea6ab6007e0d110"

      def install
        bin.install "tss"
      end
    end
  end
end
