# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PsSkeleton < Formula
  desc "Yet another PS auto-generator"
  homepage "https://github.com/maleynikov/homebrew-tap"
  version "0.1.1"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://gitlab.maleynikov.tech/api/v4/projects/12/packages/generic/ps-skeleton/0.1.1/ps-skeleton_Darwin_arm64.tar.gz?private_token=7W6yQkYCDW1pbaPmazVQ"
      sha256 "232d3310b4bf6b19372660c8da02dd694b9ae52e38069c9233e4e95aaabf987c"

      def install
        bin.install "ps-skeleton"
      end
    end
    if Hardware::CPU.intel?
      url "https://gitlab.maleynikov.tech/api/v4/projects/12/packages/generic/ps-skeleton/0.1.1/ps-skeleton_Darwin_x86_64.tar.gz?private_token=7W6yQkYCDW1pbaPmazVQ"
      sha256 "7c757a6548708669dc2776d601cd9e0b719449c30bb5c222b51830890749e4b6"

      def install
        bin.install "ps-skeleton"
      end
    end
  end
end
