# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PsSkeleton < Formula
  desc "Yet another PS auto-generator"
  homepage "https://github.com/maleynikov/homebrew-tap"
  version "0.8.1"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://gitlab.maleynikov.tech/api/v4/projects/12/packages/generic/skeleton/0.8.1/ps-skeleton_Darwin_arm64.tar.gz?private_token=7W6yQkYCDW1pbaPmazVQ"
      sha256 "2cdccb654b98519f38f2b101f96388aac83f9ebd3d8d04975bbe17c774d5baf8"

      def install
        bin.install "ps-skeleton"
      end
    end
    if Hardware::CPU.intel?
      url "https://gitlab.maleynikov.tech/api/v4/projects/12/packages/generic/skeleton/0.8.1/ps-skeleton_Darwin_x86_64.tar.gz?private_token=7W6yQkYCDW1pbaPmazVQ"
      sha256 "a98280c07226b427635d3c417698c12328cf4bd35f61ea7a685e7a4d65e3de3e"

      def install
        bin.install "ps-skeleton"
      end
    end
  end
end
