# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skeleton < Formula
  desc "Yet another PS auto-generator"
  homepage "https://github.com/maleynikov/homebrew-tap"
  version "0.10.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://gitlab.maleynikov.tech/api/v4/projects/12/packages/generic/ps-skeleton/0.10.0/ps-skeleton_Darwin_arm64.tar.gz?private_token=7W6yQkYCDW1pbaPmazVQ"
      sha256 "d9a2fda80ef886d79012c9b132e69c161fccc3b2f2396f89ad65a906d2a351a3"

      def install
        bin.install "ps-skeleton"
      end
    end
    if Hardware::CPU.intel?
      url "https://gitlab.maleynikov.tech/api/v4/projects/12/packages/generic/ps-skeleton/0.10.0/ps-skeleton_Darwin_x86_64.tar.gz?private_token=7W6yQkYCDW1pbaPmazVQ"
      sha256 "e1d77a47ed6964fd0d6182fe084ebcea8dfb63493c29c6ff401cd2631e5d3d40"

      def install
        bin.install "ps-skeleton"
      end
    end
  end
end
