# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skeleton < Formula
  desc "Yet another PS auto-generator"
  homepage "https://github.com/maleynikov/homebrew-tap"
  version "0.8.2"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://gitlab.maleynikov.tech/api/v4/projects/12/packages/generic/skeleton/0.8.2/skeleton_Darwin_arm64.tar.gz?private_token=7W6yQkYCDW1pbaPmazVQ"
      sha256 "de254669b4b13e3124c5026e5b82a7c1ceee58d35439e161bc9a39e719bfcabe"

      def install
        bin.install "ps-skeleton"
      end
    end
    if Hardware::CPU.intel?
      url "https://gitlab.maleynikov.tech/api/v4/projects/12/packages/generic/skeleton/0.8.2/skeleton_Darwin_x86_64.tar.gz?private_token=7W6yQkYCDW1pbaPmazVQ"
      sha256 "f55dc9b762c25fce21eaf600adfef24e8639cb8433cb055c7b4158be4ad3cab0"

      def install
        bin.install "ps-skeleton"
      end
    end
  end
end
